# Generated by Django 4.1.3 on 2022-11-23 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Autotrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=35)),
                ('member_access_key', models.CharField(max_length=200)),
                ('member_secret_key', models.CharField(max_length=200)),
            ],
        ),
    ]
