# Generated by Django 4.1.3 on 2022-11-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotrading', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Autotrade_list',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_id', models.CharField(max_length=35)),
                ('side', models.CharField(max_length=30)),
                ('price', models.IntegerField(null=True)),
                ('created', models.CharField(max_length=100)),
                ('volume', models.IntegerField(null=True)),
            ],
        ),
    ]
