# Generated by Django 4.1.3 on 2022-11-28 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autotrading', '0002_autotrade_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autotrade_list',
            name='price',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='autotrade_list',
            name='volume',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
